# Site wide configuration

title: PPPS 2019
locale: en_US
description: 2019 IEEE Pulsed Power and Plasma Science Conference
logo: images/site-logo.png
search: true
url: "https://ppps2019.github.io"

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  #- jekyll-gist
  - jekyll-seo-tag
  - jekyll-paginate
  #- jekyll-feed
# seems like the feed broke on the update to 0.9.2: log below
#asrich$ bundle update
#Fetching gem metadata from https://rubygems.org/...........
#Fetching version metadata from https://rubygems.org/..
#Fetching dependency metadata from https://rubygems.org/.
#Resolving dependencies...
#Using public_suffix 2.0.5
#Using colorator 1.1.0
#Using multipart-post 2.0.0
#Installing ffi 1.9.18 (was 1.9.17) with native extensions
#Using forwardable-extended 2.6.0
#Installing sass 3.4.24 (was 3.4.23)
#Installing rb-fsevent 0.10.1 (was 0.9.8)
#Installing kramdown 1.14.0 (was 1.13.2)
#Installing liquid 4.0.0 (was 3.0.6)
#Using mercenary 0.3.6
#Using rouge 1.11.1
#Using safe_yaml 1.0.4
#Using bundler 1.14.5
#Installing addressable 2.5.1 (was 2.5.0)
#Installing faraday 0.12.1 (was 0.11.0)
#Installing rb-inotify 0.9.10 (was 0.9.8)
#Using pathutil 0.14.0
#Using jekyll-sass-converter 1.5.0
#Using sawyer 0.8.1
#Using listen 3.0.8
#Installing octokit 4.7.0 (was 4.6.2)
#Using jekyll-watch 1.5.0
#Installing jekyll-gist 1.4.1 (was 1.4.0)
#Installing jekyll 3.5.0 (was 3.4.1)
#Installing jekyll-feed 0.9.2 (was 0.9.1)
#Installing jekyll-sitemap 1.1.1 (was 1.0.0)
#Bundle updated!

feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: "news/page:num/"

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
#exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  info_articles:
    output: true
    permalink: /:path/:title:output_ext

defaults:
  - scope:
      path: ""
      type: info_articles
    values:
      layout: page

# Site owner
owner:
  name: Steve Richardson
  avatar: steve-richardson-photo.jpg
  email: steve.richardson@ppps0219.org
  disqus-shortname:
  twitter: ppps2019
  facebook: #username
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
